### PR TITLE
Up the max frequency in SPI mode and fix a bug

### PR DESCRIPTION
**Pull request by phdussud**
in SPI mode fix the omission to set TMS low before the transfer TDI

### CODE REVIEW

**Comment by jeanthom** [comment]
Thanks for your contribution! Should I backport this fix to DirtyJTAG 1?

**Comment by phdussud** [comment]
Hello, 
The bug is only present in Jtag2 in the SPI implementation. The main branch does not have a SPI implementation.
Thanks!

**Comment by phdussud** [comment]
Another question.... I finally noticed that we should not support setting tms, tdi and tck independently because tms and tdi are clocked by tck. It would make things faster if we could support one command that would set tms, tdi, then clock tck and optionally rreturn  the value tdo read when tck was high. We send only one USB packet and maybe read one instead of sending one, reading one and sending another one. 
What do you think?

**Comment by jeanthom** [comment]
Are you talking about CMD_SETSIG? If so this command is here just to support UrJTAG.

**Comment by phdussud** [comment]
Yes, I am taking about the combination of CMD_SETSIG, CMD_GETSIG, CMD_SETSIG. It also used in openFPGALoader, and I bet that the OpenOCD plugin uses it as well.
________________________________

**Comment by jeanthom** [comment]
I insist on keeping CMD_SETSIG/CMD_GETSIG as is this part of what UrJTAG requires. Maybe we could add a command modifier to CMD_CLK to return TDO when we need it?

May I suggest you continuing this discussion in #77? That would help keep track of all the discussion related to the DirtyJTAG 2.0 revision.

**Pull request merged**
