### PR TITLE
Improve Docker build support

### LINKED ISSUE #96: Use Docker build --output ?
Docker new argument `--output` could be used to output the .bin files from the build:

https://matt-rickard.com/non-obvious-docker-uses

It is not clear which version of Docker is required.

### PR DESCRIPTION
**Pull request by jeanthom**
Fixes #96

### CODE REVIEW

**Comment by zoobab** [comment]
I will try it out asap, but it looks ok to me.

**Comment by zoobab** [comment]
It does not build for me, you have to add:

RUN git submodule init
RUN git submodule sync
RUN git submodule update

to get the unicore-mx library.

**Comment by jeanthom** [comment]
Is it a good deployment practice for Docker to perform Git commands inside a Docker container? I wasn't doing it in the first place because submodule cloning is supposed to be performed by `docker build`.

**Comment by zoobab** [comment]
I have not tried this actually:

$ docker build https://github.com/jeanthom/DirtyJTAG.git --output type=tar,dest=dirtyjtag.tar

I cloned the repo and did a 'docker build .' 

Will try the first method later on...

**Pull request merged**
